default_cmake_build &&

install -m 0664 $SOURCE_DIRECTORY/application/resources/multimc/scalable/multimc.svg /usr/share/pixmaps/ &&
install -m 0664 $SCRIPT_DIRECTORY/multimc.desktop /usr/share/applications/
