
OPTS+=" --enable-rgui \
        --enable-materialui \
        --enable-xmb \
        --enable-ozone \
        --enable-dylib "

./configure --build=$BUILD            \
             --prefix=/usr             \
             --sysconfdir=/etc         \
             --mandir=/usr/share/man   \
             $OPTS &&

default_make
